### PR TITLE
Added "targetframe" option, to set links default target frame.

### PR DESCRIPTION
**Pull request by nagylakas**
This is my first pull request on github, so I apologize if I would have done something wrong.

### CODE REVIEW

**Comment by tomalec** [comment]
Thanks for contribution!
I'm glad you choose us, for your first PR :)

However, I'm not sure if this regexp if safe thing to do.
They may be variaty of cases when it's not desired, like
- `a href=` in a code block:
   ````md
   [link to be changed](http://somewhere.com/)
   ```
   <a href="path.html">This is just a sample</a>
   ```
   ````
- `<a>` which already has target
   ````md
   [link to be changed](http://somewhere.com/)
   <a href="path.html" target="smth">HTML link</a>
   ```` 
- Just `a href=` as a text
   ````md
   [link to be changed](http://somewhere.com/)
   and a href="which should not get changed
   ```` 
- Given `element.targetFrame` contains `"`

Maybe it's safer just to attach it from the outside via event like
```html
<juicy-markdown on-value-changed="updateAnchors">
...
<script>
// ...
updateAnchors: function(){
    Array.prototype.forEach.call(this.querySelectorAll('a:not([target])'), function(anchor){ anchor.setAttribute('target', targetFrame);})
```

Also overwriting/scoping target is not a markdown thingy. Maybe then we could emerge HTML composition and [Unix do one thing philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well)
And do something like `<framed-markdown>` or `<scoped-markdown>` which will use `<juicy-markdown>` in Shadow DOM and do this target overwriting on `value-changed` event.

//cc @warpech

**Comment by warpech** [comment]
I agree with @tomalec. It can be applied externally using DOM events.

`juicy-markdown` is just a wrapper for [`marked`](https://github.com/chjj/marked). We should not add markdown-specific features on top of it, beucase we will not be able to maintain them. And sometimes they might go in conflict with `marked`. Just make it possible to forward the configuration to `marked`. 

@nagylakas could you check if `marked` supports adding `target` attribute on Markdown parsing level?

**Comment by warpech** [comment]
Ping @nagylakas, any interest in this still?

**Comment by warpech** [comment]
Closing as won't fix. Thanks a lot @nagylakas for your interest anyway, we are happy to help if needed!

**Pull request closed without merging**
